server:
  port: 9000
logging:
  config: classpath:log4j2-spring.xml

# big-file-upload
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


# diy
make-html-domain: "http://192.168.68.57:9000/index?htmlStr="


